name: CI

on:
  "push":
    branches: [ros2]

jobs:
  build:
    name: Build on ros ${{ matrix.ros_distribution }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            ros_distribution: "foxy"
      fail-fast: false
    steps:
      - name: Setup ROS2 ${{ matrix.ros_distribution }}
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build PKGs
        run: 
          ls -l ${{github.workspace}};
          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash;
          mkdir -p ${{github.workspace}}/ros2_ws/src ;
          cd ${{github.workspace}}/ros2_ws/src && cp -r ${{github.workspace}}/ .;
          cd ${{github.workspace}}/ros2_ws/ && colcon build --packages-up-to car_demo;
      - name: Cache Build Files
        uses: actions/cache@v3
        with:
          path: |
            ${{github.workspace}}/ros2_ws/build
            ${{github.workspace}}/ros2_ws/install
          key: build-${{ matrix.os }}-${{ matrix.ros_distribution }}
  test:
    needs: build
    name: Test on ros ${{ matrix.ros_distribution }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            ros_distribution: "foxy"
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Restore build files from cache
        uses: actions/cache@v3
        with:
          ref: ros2
          path: |
            ${{github.workspace}}/ros2_ws/build
            ${{github.workspace}}/ros2_ws/install
          key: build-${{ matrix.os }}-${{ matrix.ros_distribution }}
      - name: Test
        run: |
          set -e
          . /opt/ros/${{ matrix.ros_distribution }}/setup.sh
          source /opt/ros/${{ matrix.ros_distribution }}/setup.bash;
          ls -l ${{github.workspace}}/ros2_ws;
          cd ${{github.workspace}}/ros2_ws/ && colcon test --packages-up-to car_demo --event-handlers console_cohesion+
