name: CI

on:
  "push":
    branches: [ros2]

jobs:
  build:
    name: Build on ros ${{ matrix.ros_distribution }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            ros_distribution: "foxy"
      fail-fast: false
    steps:
      - name: Setup ROS2 ${{ matrix.ros_distribution }}
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build PKGs
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: car_demo prius_description prius_msgs
          target-ros2-distro: foxy
          skip-tests: true
  test:
    needs: build
    name: Test on ros ${{ matrix.ros_distribution }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        include:
          - os: ubuntu-20.04
            ros_distribution: "foxy"
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}
      - name: Test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: car_demo prius_description prius_msgs
          target-ros2-distro: foxy
          skip-tests: false
  deploy:
    needs: test
    name: Deploy to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/CD.yml
